version: 2
jobs:
  test:
    docker:
      - image: node:10.15.0
    steps:
      - checkout
      - run:
          name: npm install
          command: |
            sudo npm install -g npm@latest
            npm install
      - run:
          name: lint sources
          command: npm run lint
      - run:
          name: run unittests with coverage
          command: npm run test

workflows:
  per-commit:
    jobs:
      - test
